export const warmQuotes = [
  "Gia đình là nơi cuộc sống bắt đầu và tình yêu không bao giờ kết thúc.",
  "Bữa cơm ngon nhất là bữa cơm có đông đủ các thành viên gia đình.",
  "Hôm nay, bạn đã nói lời cảm ơn hay yêu thương với bố mẹ chưa?",
  "Nhà không cần quá lớn, chỉ cần có đủ tình yêu và tiếng cười.",
  "Một cái ôm ấm áp có thể xua tan mọi mệt mỏi của ngày dài.",
  "Lắng nghe là chìa khóa để thấu hiểu và xích lại gần nhau hơn.",
  "Gia đình là điểm tựa vững chắc nhất khi bạn gặp khó khăn.",
  "Niềm vui lớn nhất của cha mẹ là thấy con cái trưởng thành và hạnh phúc.",
  "Hãy dành chút thời gian tối nay để hỏi han ngày hôm nay của các thành viên khác nhé!",
  "Mỗi khoảnh khắc bên gia đình đều là một món quà vô giá của thời gian.",
  "Dù đi xa đến đâu, nhà vẫn luôn là nơi bình yên nhất để trở về.",
  "Yêu thương không chỉ là lời nói, yêu thương là sự quan tâm từ những điều nhỏ nhặt.",
  "Hôm nay, hãy thử rủ một thành viên trong nhà cùng đi dạo hoặc làm việc nhà chung nhé.",
  "Gia đình không phải là một điều quan trọng, gia đình là tất cả mọi thứ.",
  "Một lời khen chân thành dành cho người thân hôm nay sẽ mang lại nụ cười cả ngày dài.",
  "Hãy kiên nhẫn lắng nghe lời khuyên của cha mẹ, đó là trải nghiệm cả đời của họ.",
  "Bình yên là khi mở cửa bước vào nhà và thấy những người thân yêu vẫn khỏe mạnh, vui tươi.",
  "Đừng để chiếc điện thoại làm khoảng cách giữa bạn và gia đình thêm xa cách.",
  "Món quà ý nghĩa nhất bạn có thể tặng gia đình mình chính là thời gian của bạn.",
  "Gia đình là nơi chúng ta học cách yêu thương, tha thứ và chia sẻ.",
  "Hôm nay, hãy hỏi mẹ xem mẹ có mệt không và phụ mẹ chuẩn bị bữa tối nhé.",
  "Bố luôn ít nói, nhưng tình yêu của bố dành cho bạn luôn lặng thầm và vững chãi.",
  "Mỗi gia đình là một câu chuyện, hãy cùng nhau viết nên những trang sách thật đẹp.",
  "Yêu thương gia đình là liều thuốc chữa lành tốt nhất cho mọi tổn thương ngoài xã hội.",
  "Hôm nay, hãy ôm lấy người thân của bạn lâu hơn một chút nhé.",
  "Không có tình yêu nào vĩ đại và vô điều kiện như tình yêu của cha mẹ.",
  "Một tin nhắn hỏi thăm nhẹ nhàng lúc giữa ngày sẽ khiến người thân cảm thấy được quan tâm.",
  "Nhớ lại những kỷ niệm vui vẻ của gia đình là cách tuyệt vời để sưởi ấm tâm hồn.",
  "Hãy tôn trọng sự khác biệt của mỗi thành viên, đó là chìa khóa giữ gìn sự hòa thuận.",
  "Gia đình giống như những nhánh của một cái cây, chúng ta lớn lên theo các hướng khác nhau nhưng gốc rễ vẫn là một.",
  "Hôm nay là một ngày tuyệt vời để cùng cả nhà ăn một bữa cơm thật vui vẻ và đầm ấm.",
  "Tiếng cười của trẻ nhỏ và nụ cười của người già là phúc lành lớn nhất của một ngôi nhà.",
  "Đôi khi, chỉ cần một cái gật đầu thấu hiểu cũng đủ làm tan chảy mọi giận hờn.",
  "Hãy học cách xin lỗi và tha thứ khi làm tổn thương những người thân yêu.",
  "Gia đình là nơi bạn có thể là chính mình nhất mà không sợ bị phán xét.",
  "Hôm nay, hãy pha cho bố một tách trà ấm và lắng nghe bố kể chuyện xưa nhé.",
  "Thời gian trôi qua rất nhanh, hãy trân trọng từng phút giây được ở bên cạnh cha mẹ.",
  "Hạnh phúc không nằm ở những điều xa xôi, nó ẩn hiện ngay trong căn bếp ấm cúng của nhà bạn.",
  "Một lời động viên kịp thời từ gia đình có thể tiếp thêm sức mạnh vượt qua mọi giông bão.",
  "Gia đình là trường học đầu tiên dạy ta cách làm người tử tế.",
  "Hãy chia sẻ những áp lực công việc với gia đình, họ luôn sẵn sàng lắng nghe bạn.",
  "Hôm nay, hãy gửi một bức ảnh chụp chung của gia đình vào nhóm chat chung nhé.",
  "Bố mẹ có thể không cho bạn mọi thứ bạn muốn, nhưng họ đã cho bạn những gì tốt nhất họ có.",
  "Sự gắn kết gia đình được vun đắp từ những thói quen nhỏ mỗi ngày.",
  "Nhà là nơi dù bạn có mắc sai lầm thế nào, cửa vẫn luôn rộng mở đón bạn.",
  "Hôm nay, hãy chuẩn bị một bữa sáng nhỏ cho người bạn yêu thương nhé.",
  "Tình yêu thương gia đình giống như dòng sông, chảy mãi không bao giờ cạn.",
  "Hãy nhớ rằng, gia đình luôn là hậu phương vững chắc nhất trong mọi quyết định của bạn.",
  "Sự quan tâm âm thầm của anh chị em ruột thịt luôn là một điểm tựa ấm áp.",
  "Hôm nay, hãy dành một lời chúc ngày mới tốt lành đến cả nhà.",
  "Một ngôi nhà hạnh phúc là nơi tràn ngập sự thấu hiểu và sẻ chia gánh nặng.",
  "Trân trọng những gì cha mẹ đã hy sinh để chúng ta có được ngày hôm nay.",
  "Hôm nay, hãy giúp người thân làm một việc mà họ vẫn đang trì hoãn.",
  "Gia đình là nơi duy nhất chấp nhận cả những khuyết điểm lớn nhất của bạn.",
  "Hãy tạo ra thật nhiều kỷ niệm đẹp bên gia đình để làm hành trang suốt cuộc đời.",
  "Không có bữa ăn nhà hàng nào ngon bằng cơm mẹ nấu với tình yêu thương.",
  "Hôm nay, hãy lắng nghe tâm sự của em trai/em gái hoặc anh/chị của bạn.",
  "Một nụ cười của cha mẹ có thể xua tan mọi áp lực mà bạn đang đối mặt.",
  "Nhà là nơi bão dừng sau cánh cửa.",
  "Hãy trân quý những ngày tháng cả gia đình còn được khỏe mạnh ở bên nhau.",
  "Hôm nay, hãy thử gọi điện về nhà chỉ để nghe giọng nói của người thân.",
  "Tình yêu thương của gia đình là nguồn năng lượng vô tận giúp bạn tiến về phía trước.",
  "Hãy luôn đặt gia đình ở một vị trí trang trọng nhất trong trái tim bạn.",
  "Một cái ôm siết chặt từ con cái là niềm hạnh phúc lớn nhất của cha mẹ.",
  "Hãy dành cho người thân những lời dịu dàng nhất, vì họ xứng đáng nhận được điều đó.",
  "Hôm nay, hãy cùng cả nhà xem một bộ phim ý nghĩa hoặc chơi một trò chơi nhỏ.",
  "Sự bình yên trong tâm hồn bắt nguồn từ sự hòa thuận trong gia đình.",
  "Cha mẹ là người duy nhất sẵn sàng hy sinh cả cuộc đời mà không đòi hỏi đền đáp.",
  "Hãy viết một mảnh giấy note nhỏ gửi lời yêu thương và dán trên tủ lạnh hôm nay nhé.",
  "Gia đình là nơi nuôi dưỡng những ước mơ của bạn.",
  "Dành thời gian chất lượng cho gia đình không bao giờ là lãng phí.",
  "Hôm nay, hãy chủ động dọn dẹp phòng khách để tạo không gian sạch sẽ cho cả nhà ngồi trò chuyện.",
  "Một tách trà nóng và những lời tâm sự chân thành sẽ kéo các thành viên lại gần nhau.",
  "Mối quan hệ gia đình cần được chăm sóc và tưới mát bằng sự quan tâm mỗi ngày.",
  "Hãy nói lời xin lỗi nếu hôm qua bạn lỡ lời làm người thân buồn lòng.",
  "Cha mẹ luôn dõi theo từng bước đi của bạn với tất cả niềm tự hào.",
  "Hôm nay, hãy dành 10 phút ngồi yên lặng bên cạnh ông bà và nghe họ kể chuyện.",
  "Sự chia sẻ công việc nhà giúp thấu hiểu gánh nặng của nhau hơn.",
  "Nhà là nơi lưu giữ những tiếng cười giòn giã nhất thuở ấu thơ.",
  "Hãy luôn tin rằng, dù thế giới có quay lưng, gia đình vẫn luôn đứng về phía bạn.",
  "Hôm nay, hãy mua một món quà nhỏ (như một túi trái cây) mang về cho cả nhà cùng ăn.",
  "Gia đình là chốn nương náu an toàn nhất giữa cuộc đời đầy biến động.",
  "Một lời cảm ơn cha mẹ vì những bữa cơm ngon mỗi ngày là điều rất nên làm.",
  "Hãy gìn giữ những truyền thống tốt đẹp của gia đình mình.",
  "Sự thấu hiểu trong gia đình giúp ta biết cách yêu thương một cách đúng đắn.",
  "Hôm nay, hãy dành một lời khen cho sự cố gắng của anh/chị/em mình.",
  "Tình cảm gia đình là thứ tài sản quý giá nhất mà tiền bạc không mua nổi.",
  "Nhà là nơi chúng ta tìm thấy sự ấm áp ngay cả trong những ngày đông lạnh giá nhất.",
  "Hãy để tình yêu thương dẫn lối cho mọi cuộc trò chuyện trong gia đình bạn.",
  "Hôm nay, hãy chụp một tấm ảnh gia đình lưu giữ khoảnh khắc sum vầy này nhé.",
  "Sự trưởng thành của bạn là niềm an ủi lớn nhất cho những nhọc nhằn của cha mẹ.",
  "Hãy luôn dành sự kiên nhẫn cao nhất cho những người thân yêu của mình.",
  "Nhà là nơi bạn luôn được chào đón trở về với vòng tay ấm áp.",
  "Hôm nay, hãy tắt wifi 1 tiếng buổi tối để cả nhà cùng ngồi trò chuyện trực tiếp.",
  "Mỗi bữa cơm gia đình là một cơ hội để gắn kết và chia sẻ buồn vui.",
  "Yêu thương gia đình chính là gốc rễ của mọi tình yêu thương khác trên đời.",
  "Hãy biết ơn vì chúng ta vẫn còn một mái nhà để về và những người thân để yêu thương.",
  "Một lời hỏi thăm sức khỏe chân thành hôm nay sẽ sưởi ấm lòng người lớn tuổi trong nhà.",
  "Gia đình là nơi lưu giữ trọn vẹn nhất những ký ức đẹp đẽ của cuộc đời bạn.",
  "Hôm nay và mỗi ngày sau, hãy trân trọng và yêu thương gia đình nhiều hơn nữa nhé!"
];
